### ISSUE TITLE
Определить формат системы диалогов

### ISSUE THREAD

**Issue by SDesya74** [hpmor-game/hpmor#7]
В игре будут диалоги с NPC, "диалоги" с предметами, происходящие в момент взаимодействия игрока с ними. Для удобства описания диалогов, я решил сделать для них специальный декларативный язык разметки, в котором можно будет описывать то, как будет происходить диалог между персонажами.

Список требований к языку, которые я сейчас вижу:
- язык должен быть простым и лаконичным, с минимумом ключевых слов и без необходимости указывать каждой реплике того, кто её сказал (после указания автора реплики, все последующие будут оцениваться как высказанные этим же персонажем до тех пор, пока не будет указано обратное)
- нужны описания происходящего, которые не имеют автора, например для описания предметов
- должна быть возможность указания эмоций для говорящего, в зависимости от которых можно будет менять аватарку персонажу
- текст должен быть экспрессивен, надо иметь возможность указать эмоции с помощью изменения стиля, цвета текста, или добавления эффектов типа дрожания букв в тексте
- должна быть настройка для изменения способа вывода текста на экран (побуквенно, целыми словами) и возможность добавлять паузы между ними
- должно быть ветвление, позволяющее задавать игроку вопросы, на которые он отвечает и, в зависимости от ответа, его будет перекидывать на другой фрагмент диалога, расположенный в этом же файле под определённой меткой, или же на фрагмент диалога в другом файле, также отмеченный меткой
- нужны события, происходящие в момент достижения какого-то места в диалоге и на которые можно реагировать из кода снаружи, чтобы обрабатывать это событие. Например, в диалоге написано, как гг открывает дверь, и после этой реплики проигрывается анимация открытия двери.
- в диалогах должны быть заданные снаружи значения, чтобы в зависимости от них по-разному проигрывать этот диалог

Также нужно обсудить следующие вопросы:
- как будут работать переводы: каждый файл диалогов будет переведён на другой язык отдельно, или же сами диалоги внутри будут использовать ключи, переводы которым будут представлены в папке с переводами?
- нужна ли возможность NPC общаться между собой?
- должны ли диалоги иметь возможность быть проигранными без привязки к конкретным персонажам? Например, рандомный диалог двух NPC не должен знать, какие конкретно NPC его говорят, чтобы можно было запускать диалоги рандомно
- должна ли быть возможность получения некоторых параметров персонажа, например его имени и пола, чтобы вышеупомянутые рандомные диалоги нормально работали для любых ситуаций?

Простейший пример разговора между двумя NPC с репликой, описывающей поведение одного из персонажей:

![Image](https://user-images.githubusercontent.com/41489405/179773928-3b837568-0c9f-4371-9150-620ecce31308.png)

Источники вдохновения:
- https://youtu.be/DlL_20x0QH8
- https://youtu.be/1LlF5p5Od6A

**Comment by SDesya74** [comment]
## Комментарии

Комментарии объявляются после ```//```

```js
Обычный текст // комментарий
```

## Персонажи и состояния

```js
@name // персонаж
@:state // состояние
@name:state // персонаж + состояние

@ // описательный текст от рассказчика
```

## Метки

```js
#anchor // создание метки в этом файле
```

## Перемещения по меткам

```js
:move #anchor // перемещение на метку в этом файле
:move #file/anchor // перемещение на метку в другом файле
:back // возвращение на место, откуда было произведено последнее перемещение на метку
```

## Меню

Пример меню для перемещения между метками:

```js
:menu text
:opt(#anchor) text // кнопка выбора, перемещающая на метку в этом файле
:opt(#file/anchor) text // кнопка выбора, перемещающая на метку в другом файле
:opt(:state; #anchor) text // кнопка выбора, перемещающая на метку, а при наведении изменяет состояние текущего персонажа
:opt(@name:state; #anchor) text // кнопка выбора, перемещающая на метку, а при наведении изменяет состояние персонажа @name
```

Пример меню, для выбора значения локальной переменной:

```js
:menu(var_name) text // текст меню
:opt(=value) text // кнопка выбора, устанавливающая переменной var_name значение value
:opt(=value2) text2 // кнопка выбора, устанавливающая var_name значение value2
:opt(=value3; @name:state; #anchor) text3 // кнопка выбора, устанавливающая var_name значение value3, при наведении на кнопку устанавливает состояние персонажу и перемещает диалог на метку #anchor
```

## События

```js
:event "event_name" // вызов ивента
```

## Условия

```js
:if condition1
    Будет отрисовано, если condition1 == true
:elseif condition2
    Будет отрисовано, если condition2 == true
:else
    Будет отрисовано в противном случае
:endif
```

**Comment by USBashka** [comment]
Насчёт вопросов

- Один файл на язык, без ключей (так как теги повествовсния должны быть в строке, и если хранить строки отдельно, эта логика улетит)
- Да, можно добавлять адресата к реплике, если это не игрок
- Нет
- Да, но для другого

**Comment by SDesya74** [comment]
> Один файл на язык, без ключей (так как теги повествовсния должны быть в строке, и если хранить строки отдельно, эта логика улетит)

Согласен

> Да, можно добавлять адресата к реплике, если это не игрок

Тогда надо придумать для них синтаксис. Я предлагаю ```@alice:state > @bob:state```, описывающий, что Алиса говорит с Бобом

> Нет

Тогда исчезает расширяемость и переиспользуемость диалогов. Нельзя будет проиграть рандомный диалог от лица любого персонажа

> Да, но для другого

А для чего, если не для переиспользуемости?

**Comment by USBashka** [comment]
> Тогда исчезает расширяемость и переиспользуемость диалогов

Ладно, можно сделать кейворды вроде `#0`, `#1`, `#2` и т. д. для каких-нибудь рандомных челов. Но в основном лучше оставить привязку к конкретным персам

> А для чего, если не для переиспользуемости?

Эээаа.. забыл. А, чтоб вставлять инфу о происходящем. Например, о количестве баллов факультета или очков Квиррелла. Но этот функционал связан с обычным функционалом переменных (который _надеюсь_ ты проддууумал (а если нет, то можно пока обойтись без него, не самое главное))

**Comment by SDesya74** [comment]
> Ладно, можно сделать кейворды вроде #0, #1, #2 и т. д. для каких-нибудь рандомных челов. Но в основном лучше оставить привязку к конкретным персам

Чем лучше то? Текущая спецификация покрывает и кейворды, и привязку к конкретным персам, поскольку персонажи будут указываться из кода. Ничего не мешает договориться, что ```@harry``` - это ГГ, а в коде я всегда буду указывать ГГ на этот кейворд. Но если диалог не зависит от тех, кто в нём говорит, мы просто указываем им кейворды типа ```@guy_1``` и ```@guy_2```.

> А, чтоб вставлять инфу о происходящем. 

В текущей спецификации значений в принципе нет, предлагаю придумать их попозже. В их реализации будет много проблем, в том числе то, что их надо будет выделять в список, как метки с персонажами.

**Comment by USBashka** [comment]
`@guy_1` и `@guy_2`? Звучит неплохо, одобряю.

Для переменных я уже предложил тег `call`, который возвращает в текст `return` функции или значение переменной. Возможно, стоит выделить их в тег `var`. Насчёт параметров конкретных персов, можно хранить их в словаре и получать через точечную нотацию с алиасом.

```gd
Harry = {
    "name": "Гарри",
    "aliases": ["Harry", "h"],
    "color": "#7777FF",
    "house": None,
    "house_points": 0,
    "quirrell_points": 0,
    "quirrell_points_total": 0
    }
```
```js
@​Hermione Лол, ты заработал [i]всего лишь[/i] [var=Harry.house_points] очков для факультета!
@​Harry:cool Зато(!) я набрал [var=Harry.quirrell_points_total] очков Квиррелла)
@Hermione:bored [small]Держи в курсе
```

И может стоит сделать более короткие алиасы, типа **h**.

**Comment by timofeiryko** [comment]
### Блок с meta инормацией

Мне кажется, нужен некий блог вначале, где можно указывать локации, ветки сюжета, участвующих в данном диалоге персонажей и т. п.

### Переменные и функции

Это явно нужный функционал. При этом нужна возможность вызывать "внешние" переменные, которые неизвестны при написании диалога, они же завязаны на саму игру, код. Функционал в самом диалоге создавать переменные и использовать их - что-то слишком сложное, непонятно зачем нужное, необходимо только ветвление диалогов.

Можно для эксплицитности перечислять используемые "внешние" переменные в том самом Meta блоке. Аттрибуты персонажей - удобно, можно что-то вроде упомнянутого словаря в этот же Meta блок.

Синтаксис вызова переменных должен быть очень простым, например - звездочки: `*Harry.quirrell_points_total]*`

### Алиасы

Не думаю, что это хорошая идея - диалоги должны быть легко читаемы, + наверняка будут появляться новые люди, им должно быть очень легко включиться. Если использовать текстовый редактор с нормальным автокомплитом, то при написании алиасы не нужны. Ну или можно условно перед коммитом запускать парсер, который проверяет, что с синтаксисом всё хорошо и заменяет алиасы.

### Синтаксис

А как вам идея взять какой-нибудь распространенный набор элементов синтаксиса (вроде YAML или что-то Mardown based?) и договориться, как мы что обозначаем? Тогда можно будет использовать IDE при написании диалогов: + умный автокомплит, + подсветка синтаксиса.

**Comment by SDesya74** [comment]
Пример:

```js
@bob:state

Текст от Боба

:menu
:opt(#section) Дальше // не указываем персонажа, от которого говорим

#section // предположим, что сюда можно попасть не только из меню, а откуда угодно ещё

Текст от кого? // <-- говорим об этом месте
```

Нужно понять, от кого будет написана эта реплика.
Варианты:
1. Рассказчик
2. Текущий персонаж

Вариант 1 проще в реализации и даёт явный контроль над тем, кто говорит реплику, поскольку надо будет установить персонажа явно в начале секции, или же в меню, откуда персонаж попадёт на метку. 

Вариант 2 сложнее в реализации, но он даёт расширяемость и простоту, поскольку становится необязательно прописывать персонажа в меню, чтобы секция продолжилась от его имени. Ещё этот вариант даёт огромный потенциал для багов, поскольку на метку можно попасть откуда угодно и, соответственно, нет явного понимания, кто будет говорить.

**Comment by USBashka** [comment]
Рассказчик
